### ISSUE TITLE
Invalid discovery rule value

### ISSUE THREAD

**Issue by Eslam10** [sleepka/zabbix-kubernetes-monitoring#2]
Hello @sleepka, 
I received the below error in the discovery rule after importing this template.

Invalid discovery rule value: cannot parse as a valid JSON object: invalid object format, expected opening character '{' or '[' at: 'Traceback (most recent call last):
File "/etc/zabbix/scripts/k8s-stats.py", line 65, in <module>
data = json.loads(rawdata())
File "/etc/zabbix

**Comment by Eslam10** [comment]
There was an issue in the k8s token in the python script.

**Comment by crazychatting** [comment]
had the same issue. solved it by allowing the zabbix-server in the firewall to reach the kubernetes apiserver.
