### ISSUE TITLE
Unsupported item key

### ISSUE THREAD

**Issue by lalitlsg** [sleepka/zabbix-kubernetes-monitoring#6]
its showing

active check "k8s.discovery[apiservices]" is not supported: Unsupported item key.
active check "k8s.discovery[clusters]" is not supported: Unsupported item key.
active check "k8s.discovery[componentstatuses]" is not supported: Unsupported item key.
active check "k8s.discovery[containers]" is not supported: Unsupported item key.
active check "k8s.discovery[deployments]" is not supported: Unsupported item key.
active check "k8s.discovery[nodes]" is not supported: Unsupported item key.
active check "k8s.discovery[pods]" is not supported: Unsupported item key.

in docker logs

**Comment by sleepka** [comment]
it just means you installed not correctly.
check that you you installed k8s.conf for zabbix-agent, k8s-stats.py has correct permissions, also check paths and specify correct URL to api-server and token for zabbix-user in k8s-stats.py

**Comment by lalitlsg** [comment]
Sure thanks for reply.
And some queries regarding your module :

1.If I have 3 node k8s cluster (1 master, 2 worker), so zabbix agent should
be installed on master, correct?
And can I also run zabbix agent in docker container on the master node?

2. Is your module shows the current cpu,memory,storage usage of pod and
containers.
