### ISSUE TITLE
Multiple kubernetes clusters

### ISSUE THREAD

**Issue by DonaldKallman** [sleepka/zabbix-kubernetes-monitoring#8]
How would this work with multiple kubernetes clusters on a single Zabbix host?

**Comment by jpuris** [comment]
Create a different virtual host in zabbix for each kubernetes cluster. Then each host has its own "K8S_CLUSTER_NAME" value. Then have that value in the disvovery rules

For example
Kubernetes API Services => kubernetes_stats.py[{$K8S_CLUSTER_NAME},discovery,apiservices]

Virtual host "Kubernetes VPC-1"
- {$K8S_CLUSTER_NAME} => vpc1

On Zabbix server `/usr/lib/zabbix/externalscripts/kubernetes_stats.py` file has line 
```
config_file = "/etc/zabbix/kubernetes_stats.json"
cluster = sys.argv[1]
api_server = config[cluster]["api_url"]
token = config[cluster]["access_token"]
```
`/etc/zabbix/kubernetes_stats.json` has entry
```json
{
    "vpc1": {
        "api_url": "https://kubernetes_api:6443",
        "access_token": "<ACCESS_TOKEN>"
    }
}
```

Repeat for each cluster. This is how I've set it up and it works very well.

**Comment by jpuris** [comment]
If people want a pull request with all the necessary changes, let me know and I can see what can be done.

**Comment by jkruza** [comment]
Hi @jpuris,

Nice idea, but there is one thing I don't understand...

Are you sure you're using same Python script and template as in this repo?

From what I see:
- script you're referring to has different name
- `sys.argv[1]` is already used for `stats` and `discovery`. Using it to provide cluster name would require shifting all other `sys.argv[]` indices in the code
- Template provided here does not refer to script in discovery rules, but to keys like `k8s.discovery[apiservices]`
- There would be need to change also the `.conf` file as this is the place where script invocation is defined...

So the changes are "doable", but not really that simple as you described. Or did I get this whole thing wrong???

**Comment by jpuris** [comment]
Hi @jkruza,

> script you're referring to has different name

Indeed this is the same script. I had renamed it as part of many other adjustments to suit our needs

> sys.argv[1] is already used for stats and discovery. Using it to provide cluster name would require shifting all other sys.argv[] indices in the code

Correct

**Example**
Discovery
```
kubernetes_stats.py[{$K8S_CLUSTER_NAME},discovery,apiservices]
```
Prototype
```
kubernetes_stats.py[{$K8S_CLUSTER_NAME},stats,apiservices,{#NAME},Available]
```
In script, the `sys.argv[N]` had become `sys.argv[N+1]` and `sys.argv[1]` as a new property used for cluster-name

> Template provided here does not refer to script in discovery rules, but to keys like k8s.discovery[apiservices]

Honestly I dont remember this. If it was like that when I had it set up, then this is another change I had done.

> There would be need to change also the .conf file as this is the place where script invocation is defined...

Correct

Would you like me to fork this repo and do a pull request?
Note that were currently using Zabbix 4.2, so there may need to be some template edits before you can import it, if you are using different version.

**Comment by jpuris** [comment]
@jkruza I've forked this repo and added the changes in the fork https://github.com/jpuris/zabbix-kubernetes-monitoring. No pull request as it seems there has been other updates (such as "completed" container support) to this repo that I have to add to the setup we are running.

After that I can do a pull request to add multi-cloud support.

I've got no idea what the Author has planned when it comes to this, however, said that, I'm always happy to contribute.

**Comment by jkruza** [comment]
@jpuris  - wow, I expected kind of confirmation, not the work done 😄 

Big thanks!

I'm new to Zabbix and this is really great help!

**Comment by lalitlsg** [comment]
@jpuris @jkruza does this scripts gives node usage of k8s cluster ( like cpu and memory usage of node )

**Comment by jpuris** [comment]
Offtopic. Said that, @lalitlsg I don't think so. It is pulling the state of k8s objects from its API. It does not talk to cadvisor or anything like that.
For that we use Prometheus

**Comment by lalitlsg** [comment]
ok @jpuris,  thanks for the update !
